version: "3"

services:
  test_opencdms_api:
    image: opencdms_api:0.1.0
    build:
      context: .
      dockerfile: dockerfile
    container_name: test_opencdms_api
    expose:
      - "5000"
    environment:
      - PYTHONPATH=/code/surface/api:/code/tests
      - TIMESCALEDB_TELEMETRY=off
      - PGDATA=/var/lib/postgresql/data/pgdata
      - SURFACE_SECRET_KEY=test_surface_secret_key
      - SURFACE_DATA_DIR=/home/surface/surface_data/shared
      - SURFACE_DB_ENGINE=django.contrib.gis.db.backends.postgis
      - SURFACE_DB_HOST=test_opencdms_surface_db
      - SURFACE_DB_PORT=5432
      - SURFACE_DB_NAME=test_surface_db
      - SURFACE_DB_USER=dba
      - SURFACE_DB_PASSWORD=dba
      - SURFACE_BROKER_URL=redis://redis:6379/0
      - SURFACE_DJANGO_DEBUG=False
      - LOGIN_REDIRECT_URL=/wx/stations/map/
      - LOGOUT_REDIRECT_URL=/accounts/login/
      - LRGS_EXECUTABLE_PATH=/surface/LrgsClient/bin/getDcpMessages
      - LRGS_SERVER_HOST=lrgseddn1.cr.usgs.gov
      - LRGS_SERVER_PORT=16003
      - LRGS_USER=belnms
      - LRGS_PASSWORD=BWSNlrgs2016!
      - LRGS_CS_FILE_PATH=/data/search_parameters.cs
      - LRGS_MAX_INTERVAL=719
      - ENTL_PRIMARY_SERVER_HOST=107.23.152.248
      - ENTL_PRIMARY_SERVER_PORT=2324
      - ENTL_SECONDARY_SERVER_HOST=107.23.135.182
      - ENTL_SECONDARY_SERVER_PORT=2324
      - ENTL_PARTNER_ID=2B6FDADE-CA7F-443A-AD79-2FF21CEF4857
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=test_email_host
      - EMAIL_HOST_PASSWORD=test_email_password
      - EMAIL_PORT=587
      - TIMEZONE_NAME=America/Belize
      - TIMEZONE_OFFSET=-360
      - INMET_HOURLY_DATA_URL=
      - INMET_DAILY_DATA_BASE_PATH=
      - MAP_LATITUDE=17.302212
      - MAP_LONGITUDE=-88.429595
      - MAP_ZOOM=8
      - SPATIAL_ANALYSIS_INITIAL_LATITUDE=15.8469375676
      - SPATIAL_ANALYSIS_INITIAL_LONGITUDE=-89.227
      - SPATIAL_ANALYSIS_FINAL_LATITUDE=18.5299822047
      - SPATIAL_ANALYSIS_FINAL_LONGITUDE=-87.485
      - SPATIAL_ANALYSIS_SHAPE_FILE_PATH=/surface/static/images/blz_shape.png
      - STATION_MAP_WIND_SPEED_ID=51
      - STATION_MAP_WIND_GUST_ID=53
      - STATION_MAP_WIND_DIRECTION_ID=56
      - STATION_MAP_TEMP_MAX_ID=16
      - STATION_MAP_TEMP_MIN_ID=14
      - STATION_MAP_TEMP_AVG_ID=10
      - STATION_MAP_ATM_PRESSURE_ID=60
      - STATION_MAP_PRECIPITATION_ID=0
      - STATION_MAP_RELATIVE_HUMIDITY_ID=30
      - STATION_MAP_SOLAR_RADIATION_ID=72
      - STATION_MAP_FILTER_WATERSHED=1
      - STATION_MAP_FILTER_REGION=1
      - STATION_MAP_FILTER_COMMUNICATION=1
      - MCH_DB_HOST=test_opencdms_mch_db
      - MCH_DB_USER=test_mch_db_user
      - MCH_DB_PASSWORD=test_mch_db_password
      - MCH_DB_NAME=test_mch_db
      - MCH_DB_PORT=3306
      - SECRET_KEY=test_opencdms_api_secret_key
    depends_on:
      - test_opencdms_surface_db
      - test_opencdms_mch_db
      - test_opencdms_climsoft_db
      - test_opencdms_auth_db
    command: ["pytest", "tests/integration/auth/controller/test_auth_controller.py"]

    networks:
      - test_opencdms_api_test_network

  test_opencdms_surface_db:
    image: timescale/timescaledb-postgis:2.3.0-pg13
    container_name: test_opencdms_surface_db
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=dba
      - POSTGRES_USER=dba
      - POSTGRES_DB=test_surface_db
    networks:
      - test_opencdms_api_test_network

  test_opencdms_mch_db:
    image: mysql:8.0.27
    container_name: test_opencdms_mch_db
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=test_mch_db
      - MYSQL_USER=test_mch_db_user
      - MYSQL_PASSWORD=test_mch_db_password
      - MYSQL_ROOT_PASSWORD=test_root_password
    networks:
      - test_opencdms_api_test_network

  test_opencdms_auth_db:
    image: postgres
    container_name: test_opencdms_auth_db
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
    networks:
      - test_opencdms_api_test_network
    volumes:
      - test_opencdms_auth_db_data:/var/lib/postgresql/data

  test_opencdms_climsoft_db:
    image: mariadb:10.1
    container_name: test_opencdms_climsoft_db
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=climsoft
    networks:
      - test_opencdms_api_test_network
    volumes:
      - test_opencdms_climsoft_db_data:/var/lib/mysql

networks:
  test_opencdms_api_test_network:

volumes:
  test_opencdms_auth_db_data:
  test_opencdms_climsoft_db_data:
