name: Deploy on EC2

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{secrets.AWS_PRIVATE_KEY}}
            HOSTNAME : ${{secrets.HOSTNAME}}
            USERNAME : ${{secrets.USERNAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME}
          cd /home/ubuntu/opencdms-api
          git pull origin master
          docker-compose up -d --build
          docker-compose stop opencdms-api
          sleep 30
          docker-compose up -d --build