name: Deploy on EC2 - Latest

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{secrets.AWS_PRIVATE_KEY_LATEST}}
            HOSTNAME : ${{secrets.HOSTNAME_LATEST}}
            USERNAME : ${{secrets.USERNAME}}
            HOST_FQDN: ${{secrets.LATEST_HOST_FQDN}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            export HOST_FQDN=$HOST_FQDN
            cd /home/ubuntu/opencdms-api
            git pull origin main
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml stop opencdms-api
            sleep 30
            docker-compose -f docker-compose.prod.yml up -d --build
          '